steps:
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk:slim"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        gcloud functions deploy $_FUNCTION_NAME \
          --runtime nodejs22 \
          --trigger-http \
          --entry-point $_ENTRY_POINT \
          --set-env-vars "DAYFORGE_API_BASE_URL=https://us-central1-allprojects-424621.cloudfunctions.net/dayforge-function" \
          --set-secrets "GOOGLE_CLOUD_USERNAME=projects/$_PROJECT_ID/secrets/GOOGLE_CLOUD_USERNAME:latest,GOOGLE_CLOUD_PASSWORD=projects/$_PROJECT_ID/secrets/GOOGLE_CLOUD_PASSWORD:latest" \
          --region $_REGION

substitutions:
  _PROJECT_ID: "allprojects-424621"
  _REGION: "us-central1"
  _FUNCTION_NAME: "dayforge-api-timer-trigger-proxy-function"
  _ENTRY_POINT: "dayForgeAPITimerTriggerProxy"

timeout: "600s"
